baseURL = "https://example.com/"
languageCode = "en-US"
title = "Derek Driggs"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/derek_driggs_test_new.png"
  author = "Derek Driggs"
  description = "Academic Website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "derekdriggs"
  Email         = "dtd24@cam.ac.uk"
  LinkedIn      = "derek-driggs-bb660a199/"
  # RSS           = "/blog/index.xml"

## Main Menu
# [[menu.main]]
#   name = "blog"
#   weight = 100
#   identifier = "blog"
#   url = "/blog/"
# [[menu.main]]
#   name = "projects"
#   identifier = "projects"
#   weight = 200
#   url = "/projects/"
# [[menu.main]]
#   name = "resume"
#   identifier = "resume"
#   weight = 300
#   url = "/resume/"
